exports.serverUrl = process.env.TASKIPRO_INTEGRATION_TEST_URI;

exports.apiUrl = process.env.TASKIPRO_INTEGRATION_TEST_URI + '/api';

exports.loginResourceSuffix = '/auth/login';

exports.authToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkNmRjZWI3Yzk5MDMwMTY2OTQ1ODliMiIsImRpc3BsYXlOYW1lIjoiU3lzIEFkbWluIiwiZW1haWwiOiJzeXNhZG1pbkB0YXNraXByby5jb20iLCJyb2xlcyI6WyJhZG1pbiJdLCJpYXQiOjE1Njc0Nzc0MzEsImV4cCI6MTU3MDA2OTQzMX0.Uri1jQKR1wQHSXH_sp8NG2dvoyuEkM2INSQGQcE1O58'
